### PR TITLE
Fix C++20 compilation error with char16_t stream operator

### LINKED ISSUE #170: C++20 deleted the implicit `operator<<` for `char16_t`
From @radford-for-smpte   

## Problem

  C++20 deleted the implicit `operator<<` for `char16_t` to prevent accidental misuse. This causes a compilation error when building with C++20:

  ```cpp
  error: use of deleted function 'std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, char16_t)'
```

  This affects projects using regxmllib as a Node.js native addon with Node 24+, which requires C++20.

  Solution

  Line 755 in FragmentBuilder.cpp now explicitly casts the char16_t (XMLCh) to unsigned char before streaming:

```cpp
// Before:
ss << "$#x" << std::hex << c << ";";

// After:
ss << "$#x" << std::hex << static_cast<unsigned char>(c) << ";";
```

  The unsigned char cast is semantically correct since the control flow guarantees that c < 0xFF at this point in the code (the if statement at lines 740-743 handles all other cases).

  Benefits

  -  Fixes C++20 compilation
  -  Backwards compatible with C++17 and earlier
  -  Semantically correct type cast matching the code's constraints
  -  Makes intent explicit (numeric conversion for hex formatting)

  Testing

  Verified successful compilation with both:
  - C++20 (Node.js 24 native addon build on macOS and Linux)
  - C++17 (backwards compatibility confirmed)

### PR DESCRIPTION
**Pull request by radford-for-smpte**
Closes #170 

## Problem

  C++20 deleted the implicit `operator<<` for `char16_t` to prevent accidental misuse. This causes a compilation error when building with C++20:

  ```cpp
  error: use of deleted function 'std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, char16_t)'
```

  This affects projects using regxmllib as a Node.js native addon with Node 24+, which requires C++20.

  Solution

  Line 755 in FragmentBuilder.cpp now explicitly casts the char16_t (XMLCh) to unsigned char before streaming:

```cpp
// Before:
ss << "$#x" << std::hex << c << ";";

// After:
ss << "$#x" << std::hex << static_cast<unsigned char>(c) << ";";
```

  The unsigned char cast is semantically correct since the control flow guarantees that c < 0xFF at this point in the code (the if statement at lines 740-743 handles all other cases).

  Benefits

  -  Fixes C++20 compilation
  -  Backwards compatible with C++17 and earlier
  -  Semantically correct type cast matching the code's constraints
  -  Makes intent explicit (numeric conversion for hex formatting)

  Testing

  Verified successful compilation with both:
  - C++20 (Node.js 24 native addon build on macOS and Linux)
  - C++17 (backwards compatibility confirmed)

### CODE REVIEW

File: src/main/cpp/com/sandflow/smpte/regxml/FragmentBuilder.cpp [hunk 1]
```diff
@@ -752,7 +752,7 @@ namespace rxml {
 
 				/* c is guaranteed to be less than 0xFF */
 
-				ss << "$#x" << std::hex << c << ";";
+				ss << "$#x" << std::hex << static_cast<unsigned char>(c) << ";";
```
Comment (palemieux) [inline src/main/cpp/com/sandflow/smpte/regxml/FragmentBuilder.cpp]:
```suggestion
				ss << "$#x" << std::hex << static_cast<uint16_t>(c) << ";";
```

**Review by palemieux — CHANGES_REQUESTED** [review]

**Comment by palemieux** [comment]
> Yeah trying to sort out the failure. Pretty sure it's unrelated to this change.

It might related to the change. Don't you want `ss << "$#x" << std::hex << static_cast<uint16_t>(c) << ";";` since XML character entities are 16-bit?

File: src/main/cpp/com/sandflow/smpte/regxml/FragmentBuilder.cpp (hunk 1 above)
Comment (radford-for-smpte) [reply src/main/cpp/com/sandflow/smpte/regxml/FragmentBuilder.cpp]: Yeah that's what I had originally. Makes sense.
